version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: app_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: app_pgdata 